services:

  # Serviço de Coordenação do Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # O Cluster Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # AQUI ESTÁ O SEGREDO DO KAFDROP (kafka:29092) E DO JAVA (localhost:9092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Interface visual para ver o Kafka (Acesse localhost:9000)
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      # Conecta na porta interna do Kafka
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx64M" # Otimização de memória

  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5433:5432" # Porta Externa 5433 -> Interna 5432
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: dev12345 # ATENÇÃO: Se seu Java usa dev1234, mude aqui ou no Java!
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Removi a linha do init.sql para evitar erro de arquivo não encontrado se você não tiver o script

volumes:
  postgres_data: